config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'landings/index'

  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root 'landings#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	belongs_to :user
	has_many :reviews

	searchkick text_start: [:title]

	has_attached_file :image, styles: { medium: "400x600#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  	

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def search
    if params[:search].present?
      @movies = Movie.search params[:search], fields: [{title: :text_start}]
    else
      @movies = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :length, :rating, :director, :photo, :image, :genre)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id 

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])

  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/landings/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Hello, world!
				</h2>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed navbar-inverse" role="navigation">
	<div class="navbar-header">

		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		</button> <a class="navbar-brand" href="<%= asset_path root_path %>"><img style="max-width:150px; margin-top: -15px;"
        src="<%= asset_path 'logomovies.png' %>"></a>
	</div>

	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li>
				<a href="<%= asset_path movies_path %>">Movies</a>
			</li>
			
			
		</ul>
		<ul class="nav navbar-nav navbar-right">
		
		<li><%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-left", role: "search" do  %>
		<p>
		<%= text_field_tag :search, params[:search], class: "form-control" %>
		<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
		</p>
		<% end %>
		</li>
			<li>
				<% if defined?(Devise) %>
				<% if user_signed_in? %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
						<li class="divider"></li>
						<li><%= link_to t('logout'), destroy_user_session_path, method: :delete %></li>
					</ul>
				</li>
				<% else %>
				<li><%= link_to t('login'), new_user_session_path %></li>
				<li><%= link_to t('signup'), new_user_registration_path %></li>
				<% end %>
				<% end %>
			</li>
		</ul>
	</li>
</ul>
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviereviewapp</title>
 
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

</head>
<body>

<%= render "layouts/navbar" %>

<div class="container">
<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>
</div>


</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field formmargin">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "btn btn-default" %>
  </div>
<div class="form-group">
  <div class="field formmargin">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field formmargin">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field formmargin">
  <% genre = {"Comedy":"Comedy", "Action":"Action", "Horror":"Horror", "Animation":"Animation", "Documentary":"Documentary", "Romance":"Romance", "Drama":"Drama"}  %>
  <%= f.label :genre %>
  <%= f.select :genre, genre, class: "form-control" %>
  </div>
  <div class="field formmargin">
    <%= f.label :length %><br>
    <%= f.text_field :length, class: "form-control" %>
  </div>
  <div class="field formmargin">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  <div class="field formmargin">
    <%= f.label :director %><br>
    <%= f.text_field :director, class: "form-control" %>
  </div>
  <div class="actions formmargin">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
 <% if !user_signed_in? %>
    <div class="jumbotron">
    <h1>Your favourite movies reviewed</h1>
    <p>Please sign in to write a review</p>
    <p><%= link_to "Sign up", new_user_registration_path, class: "floatleft btn btn-primary btn-lg" %></p>
    <p><%= link_to "Sign in", new_user_session_path, class: "floatright btn btn-info btn-lg" %></p>    
    </div>
 <% end  %>


 <%= link_to ' New', new_movie_path, class: "btn btn-info fa fa-plus-square-o", style: "color: white" %>
  <div class="row pagemargin">
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail cards-container card">
      <%= link_to (image_tag movie.image.url(:medium), class: "image photo"), movie %>

      </div>
    </div>
    <% end %>
  </div>

app/views/movies/new.html.erb
<div class="container well">
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>
</div>

app/views/movies/search.html.erb
<%= link_to ' Back', movies_path, class: "btn btn-primary btn-small fa fa-arrow-circle-o-left", style: "color: white"  %>

  <div class="row pagemargin">
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail cards-container card">
      <%= link_to (image_tag movie.image.url(:medium), class: "image photo"), movie %>

      </div>
    </div>
    <% end %>
  </div>

app/views/movies/show.html.erb
<div class="bodyred">
  <%= link_to ' Back', movies_path, class: "btn btn-primary btn-small fa fa-arrow-circle-o-left", style: "color: white"  %>

  <%= link_to '', edit_movie_path(@movie), class: "btn btn-warning btn-small fa fa-pencil-square-o", style: "color: white"  %>   

  <% if user_signed_in?%>
  <%= link_to "", movie_path(@movie), method: :delete, class: "btn btn-danger btn-small fa fa-trash", style: "color: white" %>
  <% end %>
  <br>
  <br>

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-5">
          <%= image_tag @movie.image.url(:medium) %>
          <div class="star-rating" data-score=<%= @avg_review %>></div>
                <em><%= "#{@reviews.length} reviews" %></em>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td><strong>Title:</strong></td>
                  <td> <%= @movie.title %></td>
                </tr>
                <tr>
                  <td><strong>Genre:</strong></td>
                  <td><%= @movie.genre %></td>
                </tr>
                <tr>
                  <td><strong>Length:</strong></td>
                  <td><%= @movie.length %></td>
                </tr>
                <tr>
                  <td><strong>Director:</strong></td>
                  <td><%= @movie.director %></td>
                </tr>
                <tr>
                  <td><strong>Rating:</strong></td>
                  <td><%= @movie.rating %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-md-7 col-offset-1">
          <h1 class="review_title"><%= @movie.title %></h1>
          <p><%= @movie.description %></p>
            <% if @reviews.blank?  %>
              <h3>No reviews just yet. Would you like to add one?</h3>
                <%= link_to "Write review", new_movie_review_path(@movie), class: "btn btn-info" %>
            <% else  %>
              <% @reviews.each do |review| %>
              <div class="reviews">
               <div class="star-rating" data-score=<%= review.rating %>></div>
                <p><%= review.comment %></p>
              </div>
            <% end %>
            <%= link_to " New Review", new_movie_review_path(@movie.id), class: "btn btn-primary fa fa-plus-square-o"  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
 $('.star-rating').raty({
   path:'/assets/',
   readOnly:true,
   score:function() {
     return $(this).attr('data-score');
   }
 });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
 $('#star-rating').raty({
   path:'/assets/',
   scoreName: 'review[rating]' 
 });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', '#' %> |
<%= link_to 'Back', '#' %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Author:</strong>
  <%= @review.user.email %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>